repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: requirements-txt-fixer
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [--max-line-length=88]
      exclude: |
            (?x)^(
                docs*|
                test*
            )$
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      args: [--multi-line=3,--trailing-comma,--force-grid-wrap=0,--use-parentheses,--line-width=88]
      exclude: |
            (?x)^(
                docs*|
                test*
            )$
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: []
      exclude: |
            (?x)^(
                docs*|
                test*
            )$
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
      exclude: |
            (?x)^(
                docs*|
                test*
            )$
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      exclude: (tests|docs)*
